# Generated by Django 3.2.21 on 2023-09-19 23:10

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_creditcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='cut_off_day',
            field=models.IntegerField(validators=[core.models.validate_day]),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='payment_due_day',
            field=models.IntegerField(validators=[core.models.validate_day]),
        ),
    ]
