# Generated by Django 3.2.21 on 2023-09-21 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_expense_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expense',
            new_name='ExpenseType',
        ),
    ]
