# Generated by Django 3.2.21 on 2023-10-26 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_expense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='expense',
            new_name='expensetype',
        ),
    ]
