# Generated by Django 3.2.21 on 2023-10-26 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_expense_expense_expensetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('effective_date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('creditcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.creditcard')),
                ('expensetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.expensetype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
