# Generated by Django 3.2.21 on 2023-10-27 03:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_creditexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditexpense',
            name='cut_off_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditexpense',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
